pipeline:
  name: remote
  identifier: remote
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {"new"}
  stages:
    - stage:
        name: test
        identifier: test
        template:
          templateRef: testtemp12
          versionLabel: "1"
          templateInputs:
            type: Deployment
            variables:
              - name: testvar
                type: String
                value: <+input>.default(false).allowedValues(true,false)
